/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
    UseAutoImport: typeof import('./../src/components/useAutoImport.vue')['default']
    UseBoolean: typeof import('./../src/components/useBoolean.vue')['default']
    UseContextFather: typeof import('./../src/components/useContextFather.vue')['default']
    UseContextGrand: typeof import('./../src/components/useContextGrand.vue')['default']
    UseContextSon: typeof import('./../src/components/useContextSon.vue')['default']
    UseEmpty: typeof import('./../src/components/useEmpty.vue')['default']
    UseEnv: typeof import('./../src/components/useEnv.vue')['default']
    UseFetch: typeof import('./../src/components/useFetch.vue')['default']
    UseI18n: typeof import('./../src/components/useI18n.vue')['default']
    UseIconify: typeof import('./../src/components/useIconify.vue')['default']
    UseJsx: typeof import('./../src/components/useJsx.vue')['default']
    UseLoading: typeof import('./../src/components/useLoading.vue')['default']
    UseLodash: typeof import('./../src/components/useLodash.vue')['default']
    UseNumber: typeof import('./../src/components/useNumber.vue')['default']
    UsePattern: typeof import('./../src/components/usePattern.vue')['default']
    UseReload: typeof import('./../src/components/useReload.vue')['default']
    UseScss: typeof import('./../src/components/useScss.vue')['default']
    UseStandard: typeof import('./../src/components/useStandard.vue')['default']
    UseStorage: typeof import('./../src/components/useStorage.vue')['default']
    UseStore: typeof import('./../src/components/useStore.vue')['default']
    UseTreeHelper: typeof import('./../src/components/useTreeHelper.vue')['default']
    UseTypeOf: typeof import('./../src/components/useTypeOf.vue')['default']
    UseUnocss: typeof import('./../src/components/useUnocss.vue')['default']
    UseVitest: typeof import('./../src/components/useVitest.vue')['default']
    UseVueuse: typeof import('./../src/components/useVueuse.vue')['default']
  }
}
